@startuml

Entity Клиент {
    Телефон
    Участник бонусной программы
    Сессия
}

Entity ПрограммаЛояльности {
    Количество бонусов
    ФИО
    Телефон
    Почта
    День рождения
    Уровень клиента
    Дата присоединения
}

Entity Меню {
    Название
    Срок действия
    Тип
}

Entity Блюдо {
    Название
    Тип
    Описание
    Цена
    Фотография
    Рекламный текст
}

Entity Ингредиент {
    Название
    БЖУ
    Калорийность
    Фотография
    Цена
    Доступность
    Максимальное количество
    Обязательность
}

Entity Комбобургер {
    Название
    Описание
    Состав
    Ограничение на ингредиенты
    Наценка
}

Entity Корзина {
    Стоимость
    Состав (блюдо-количество)
}

Entity Заказ {
    Номер
    Статус
    Дата
    Стоимость
    Способ получения
    Время получения
    Способ оплаты
}

Entity Справочник {
    Способ получения
    Способ оплаты
}

Entity Транзакция {
    Банк
    Статус
    ДатаВремя
    Сумма
    Чек
}

Entity Робот {
    Идентификатор
    Статус
    Местоположение
    Техническое состояние
}

Entity Задание {
    Идентификатор
    Описание
    Статус
    Время начала
    Время окончания
}

Entity ТехнологическаяКарта {
    Название
    Описание
    Ингредиенты
    Порядок действий
    Время приготовления
}

Клиент "1" --> "0..1" Корзина: Формирует
Клиент "1" --> "0..*" Заказ: Делает
Корзина ^-- Заказ
Блюдо "1.." --o "0..*" Корзина
Комбобургер --^ Блюдо
Блюдо "1.."  --o "1.." Меню
Ингредиент "2..10"  --o "0..*" Комбобургер
Ингредиент -- Ингредиент : Может быть в
Блюдо --o Блюдо : Связанные блюда
Заказ "1" --o "0..*" Транзакция : "Содержит"
Заказ --> Справочник : "Использует"
Клиент "1" --o "0..1" ПрограммаЛояльности : "Участвует в"

Робот "1..*" -- "0..*" Задание : "Выполняет"
Задание -- Заказ : "Связано с"
ТехнологическаяКарта -- Блюдо : "Определяет"
ТехнологическаяКарта -- Ингредиент : "Использует"

@enduml
