@startuml

Entity Клиент {
Телефон
Участник бонусной программы
Сессия
}

Entity ПрограммаЛояльности {
Количество бонусов
ФИО
Телефон
Почта
День рождения
Уровень клиента
Дата присоединения
}

Entity Меню {
Название
Срок действия
Тип
}

Entity Товар {
Название
Тип
Рекламный текст
БЖУ
Калорийность
Описание
Фотография
Цена
Связанные товары
}

Entity Ингредиент {
Название
БЖУ
Калорийность
Фотография
Цена
Доступность
Максимальное количество
Обязательность
}

Entity Комбобургер {
Описание
Состав
Ограничение на ингредиенты
Наценка
}

Entity Корзина {
Стоимость
Состав\товар-количество
}

Entity Заказ {
Номер
Статус
Дата
Стоимость
Способ получения
Время получения
Способ оплаты
}

Entity Справочник {
Способ получения
Способ оплаты
}

Entity Транзакция {
Банк
Статус
ДатаВремя
Сумма
Чек
}

Клиент "1" --> "0..1" Корзина: Формирует
Клиент "1" --> "0..*" Заказ: Забирает
Корзина ^-- Заказ
Товар "1.." --o "0.." Корзина
Комбобургер --^ Товар
Товар "1.."  --o "1.." Меню
Ингредиент "2..10"  --o "0.." Комбобургер
Ингредиент -- Ингредиент
Товар --o Товар
Заказ "1" --o "0..*" Транзакция : "содержит"
Заказ --> Справочник : "использует"
Клиент "1" --o "0..1" ПрограммаЛояльности : "участвует в"

@enduml