@startuml
actor "Customer" as c
box "Restaurant System"
participant "Order Interface" as oi
participant "Api Gateway" as gw
participant "Order Service" as os
participant "Clients Service" as cs
participant "Menu Service" as ms
participant "Inventory Service" as is
participant "Bank Service" as bs
participant "Order tableau" as ot
queue "Kafka" as kf
end box

autonumber  "<b>[0]"
opt Авторизация клиента в приложении
    c -> oi: Зайти в приложении
    activate oi
    oi -> gw : Авторизация
    activate gw
    gw -> cs : Проверка данных
    activate cs
    cs -> gw : Токен
    deactivate cs
    gw -> oi : Токен получен
    deactivate gw
end

oi -> cs : Проверка регистрации в системе
activate cs
alt Клиент зарегистрирован
    cs -> oi : Бонусы загружены
    c -> oi : Выбрать заказ из истории для повторения
    oi -> ms : Проверка доступности блюд из заказа в меню
    activate ms
    ms -> oi : Список доступных блюд
    opt Некоторые блюда недоступны
        ms -> oi : Список недоступных блюд и их аналогов
        c -> oi : Скорректировать заказ
    end
    deactivate ms
else Клиент не зарегистрирован в системе
    oi -> c : Предложение зарегистрироваться в системе
    c -> oi : Ввести данные для регистрации
    oi -> cs : Передать данные для регистрации
    cs -> oi : Подтверждение регистрации
end
deactivate cs

oi -> os : Создать заказ
activate os
os -> kf : Сообщить о создании заказа
activate kf
deactivate os
deactivate kf

oi -> c : Показать итоговый заказ
c -> oi : Подтвердить заказ

' Новый шаг: Проверка и блокировка ингредиентов
oi -> is : Проверка наличия ингредиентов
activate is
is -> oi : Ингредиенты в наличии
opt Ингредиентов недостаточно
    is -> oi : Уведомление о нехватке ингредиентов
    c -> oi : Скорректировать заказ
is -> is : Блокировка ингредиентов
is -> ms++: Сделать блюда недоступными 
is --
ms --

end 
oi -> c : Показать итоговый заказ

c -> oi : Оплатить заказ

oi -> gw : Начать оплату заказа
activate gw
gw -> bs : Проведение оплаты
activate bs

alt Успешная оплата
    bs -> gw : Оплата успешна
    deactivate bs
    gw -> oi : Сообщить клиенту
    deactivate gw
    os -> kf : Обновить статус заказа
    activate os
    ot -> ot : Показать заказ на табло
    activate ot
    deactivate os
    deactivate ot
    deactivate kf
else Оплата не прошла
    bs -> gw : Оплата неуспешна
    activate gw
    deactivate bs
    gw -> oi : Сообщить клиенту
    deactivate gw
else Банк недоступен
    bs -> gw : 500 code
    activate gw
    deactivate bs
    loop Повторная попытка оплаты
        gw -> bs : Повторить оплату
        activate bs
        deactivate bs
    end
    gw -> oi : Ошибка оплаты
    deactivate gw
end
deactivate oi
@enduml