@startuml
[*] --> ВременныйЗаказ : Новый заказ
ВременныйЗаказ --> Создан : Корзина сформирована, выбрано время\nи место получения
Создан --> ЗаказОплачен : Успешная оплата
Создан --> [*] : Не оплачен в течение 2 минут

ЗаказОплачен --> ПереданВПроизводство : Начало приготовления
ПереданВПроизводство --> Приготовлен : Заказ готов
Приготовлен --> ВВыдаче : Передача на выдачу

ВВыдаче --> Получен : Клиент забрал заказ
ВВыдаче --> Самоотказ : Заказ не забрали в течение 3 часов

Самоотказ --> [*] : Заказ отменен
Получен --> [*] : Завершен

[*] --> [*] : Информация удалена через 1 год
@enduml
