openapi: 3.0.0
info:
  title: Restaurant API
  version: 1.0.0
  description: API для работы с заказами в ресторане и программой лояльности

paths:
  /menu:
    get:
      summary: Получить меню ресторана
      operationId: getMenu
      responses:
        '200':
          description: Меню успешно получено
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    dishId:
                      type: string
                      format: uuid
                      description: Уникальный идентификатор блюда
                    name:
                      type: string
                      description: Название блюда
                    price:
                      type: number
                      format: float
                      description: Цена блюда
                    isDiscounted:
                      type: boolean
                      description: Есть ли на блюдо скидка
        '500':
          description: Внутренняя ошибка сервера

  /orders:
    post:
      summary: Добавить блюдо в корзину
      operationId: addDishToCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dishId:
                  type: string
                  format: uuid
                  description: Уникальный идентификатор блюда
                quantity:
                  type: integer
                  description: Количество порций
      responses:
        '201':
          description: Блюдо успешно добавлено в корзину
        '400':
          description: Некорректные данные
        '404':
          description: Блюдо не найдено
        '500':
          description: Внутренняя ошибка сервера

  /cart:
    get:
      summary: Просмотреть корзину
      operationId: getCart
      responses:
        '200':
          description: Корзина успешно получена
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalPrice:
                    type: number
                    format: float
                    description: Общая сумма заказа
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        dishId:
                          type: string
                          format: uuid
                          description: Уникальный идентификатор блюда
                        name:
                          type: string
                          description: Название блюда
                        quantity:
                          type: integer
                          description: Количество порций
                        price:
                          type: number
                          format: float
                          description: Цена блюда
        '500':
          description: Внутренняя ошибка сервера

  /cart/{dishId}:
    delete:
      summary: Удалить блюдо из корзины
      operationId: removeDishFromCart
      parameters:
        - name: dishId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор блюда
      responses:
        '200':
          description: Блюдо успешно удалено из корзины
        '404':
          description: Блюдо не найдено в корзине
        '500':
          description: Внутренняя ошибка сервера

  /orders/{orderId}/pay:
    post:
      summary: Оплатить заказ (возможна частичная оплата бонусами)
      operationId: payForOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор заказа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentMethod:
                  type: string
                  enum: [card, cash]
                  description: Способ оплаты
                bonusPoints:
                  type: number
                  format: float
                  description: Количество бонусов, используемых для частичной оплаты (опционально)
      responses:
        '200':
          description: Заказ успешно оплачен (с учётом бонусов)
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalPaid:
                    type: number
                    format: float
                    description: Общая сумма, оплаченная (включая бонусы)
                  bonusUsed:
                    type: number
                    format: float
                    description: Количество использованных бонусов
        '400':
          description: Некорректные данные оплаты
        '404':
          description: Заказ не найден
        '500':
          description: Внутренняя ошибка сервера

  /loyalty/register:
    post:
      summary: Регистрация в программе лояльности
      operationId: registerLoyalty
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Имя пользователя
                phoneNumber:
                  type: string
                  description: Номер телефона пользователя
                email:
                  type: string
                  format: email
                  description: Электронная почта пользователя
      responses:
        '201':
          description: Успешная регистрация в программе лояльности
        '400':
          description: Некорректные данные регистрации
        '500':
          description: Внутренняя ошибка сервера

  /loyalty/{clientId}/balance:
    get:
      summary: Проверить баланс программы лояльности
      operationId: getLoyaltyBalance
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор клиента
      responses:
        '200':
          description: Баланс программы лояльности успешно получен
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: float
                    description: Баланс программы лояльности
        '404':
          description: Клиент не найден
        '500':
          description: Внутренняя ошибка сервера

  /orders/{orderId}/cancel:
    post:
      summary: Отмена заказа
      operationId: cancelOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор заказа
      responses:
        '200':
          description: Заказ успешно отменен
        '404':
          description: Заказ не найден или уже выполнен
        '500':
          description: Внутренняя ошибка сервера
